name: Build and Deploy AMI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Packer & Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt update && sudo apt install -y packer terraform

      - name: Build HCP Packer Image
        run: |
          export HCP_CLIENT_ID=${{ secrets.HCP_CLIENT_ID }}
          export HCP_CLIENT_SECRET=${{ secrets.HCP_CLIENT_SECRET }}
          packer init ubuntu-hcp.pkr.hcl
          packer validate ubuntu-hcp.pkr.hcl
          packer build ubuntu-hcp.pkr.hcl

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy with Terraform
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export HCP_CLIENT_ID=${{ secrets.HCP_CLIENT_ID }}
          export HCP_CLIENT_SECRET=${{ secrets.HCP_CLIENT_SECRET }}
          terraform init
          terraform validate
          terraform apply -auto-approve
